set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' 

run '~/.tmux/plugins/tpm/tpm'

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind -  split-window -v
bind \\ split-window -h

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
setw -g status-style fg=colour255,bg=colour234

set-option -g mouse on

set-window-option -g mode-keys vi
