include ./nord.conf

font_family Source Code Pro Light
font_size 10.5

mouse_hide_wait 0.0

background_opacity 0.8

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_title_template "{index}"

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
