options = { noremap = true, silent = true }
vim.g.mapleader = " "

vim.keymap.set("n", "H", "10h", options)
vim.keymap.set("n", "J", "10j", options)
vim.keymap.set("n", "K", "10k", options)
vim.keymap.set("n", "L", "10l", options)

vim.keymap.set("n", "<Leader>ff", function()
	require("telescope.builtin").find_files()
end, options)
vim.keymap.set("n", "<Leader>fg", function()
	require("telescope.builtin").live_grep()
end, options)
vim.keymap.set("n", "<Leader>fb", function()
	require("telescope.builtin").buffers()
end, options)
vim.keymap.set("n", "<Leader>fc", function()
	require("telescope.builtin").current_buffer_fuzzy_find()
end, options)

vim.keymap.set("n", "<Leader>hl", function()
	require("hop").hint_lines()
end, options)
vim.keymap.set("n", "<Leader>hc", function()
	require("hop").hint_char1()
end, options)
vim.keymap.set("n", "<Leader>hw", function()
	require("hop").hint_words()
end, options)

vim.keymap.set("n", "<Leader>K", "<cmd>lua vim.lsp.buf.hover()<CR>")
vim.keymap.set("n", "gf", "<cmd>lua vim.lsp.buf.formatting()<CR>")
vim.keymap.set("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>")
vim.keymap.set("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>")
vim.keymap.set("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>")
vim.keymap.set("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>")
vim.keymap.set("n", "gt", "<cmd>lua vim.lsp.buf.type_definition()<CR>")
vim.keymap.set("n", "gn", "<cmd>lua vim.lsp.buf.rename()<CR>")
vim.keymap.set("n", "ga", "<cmd>lua vim.lsp.buf.code_action()<CR>")
vim.keymap.set("n", "ge", "<cmd>lua vim.diagnostic.open_float()<CR>")
vim.keymap.set("n", "g]", "<cmd>lua vim.diagnostic.goto_next()<CR>")
vim.keymap.set("n", "g[", "<cmd>lua vim.diagnostic.goto_prev()<CR>")

vim.keymap.set("n", "<Leader>p", "<cmd>:BufferLineCycleNext<CR>", options)
vim.keymap.set("n", "<Leader>o", "<cmd>:BufferLineCyclePrev<CR>", options)

vim.keymap.set("n", "ss", "<cmd>:split<CR>", options)
vim.keymap.set("n", "sv", "<cmd>:vsplit<CR>", options)
vim.keymap.set("n", "sh", "<C-w>h", options)
vim.keymap.set("n", "sj", "<C-w>j", options)
vim.keymap.set("n", "sk", "<C-w>k", options)
vim.keymap.set("n", "sl", "<C-w>l", options)
vim.keymap.set("n", "sH", "<C-w>H", options)
vim.keymap.set("n", "sJ", "<C-w>J", options)
vim.keymap.set("n", "sK", "<C-w>K", options)
vim.keymap.set("n", "sL", "<C-w>L", options)
vim.keymap.set("n", "s>", "<C-w>>", options)
vim.keymap.set("n", "s<", "<C-w><", options)
vim.keymap.set("n", "s+", "<C-w>+", options)
vim.keymap.set("n", "s-", "<C-w>-", options)
